### ISSUE TITLE
Test failures with python3.7 and python3.8

### ISSUE THREAD

**Issue by kitterma** [saghul/pycares#106]
Using git master as it stands now (from 20190906), I get the following test failures:

python3.7:

======================================================================
FAIL: test_idna_encoding (__main__.DNSTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/tests.py", line 453, in test_idna_encoding
    self.assertEqual(self.errorno, pycares.errno.ARES_ENOTFOUND)
AssertionError: 11 != 4

======================================================================
FAIL: test_result_not_ascii (__main__.DNSTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/tests.py", line 431, in test_result_not_ascii
    self.assertIsInstance(r.host, bytes)  # it's not ASCII
AssertionError: 'mx00.ionos.es' is not an instance of <class 'bytes'>

----------------------------------------------------------------------
Ran 45 tests in 10.426s

FAILED (failures=2)

python3.8:

======================================================================
FAIL: test_result_not_ascii (__main__.DNSTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/tests.py", line 431, in test_result_not_ascii
    self.assertIsInstance(r.host, bytes)  # it's not ASCII
AssertionError: 'mx00.ionos.es' is not an instance of <class 'bytes'>

----------------------------------------------------------------------
Ran 45 tests in 9.865s

FAILED (failures=1)

Both of which are far better than 3.0 does.  It would be nice if you could have a look and do a new release that passes all the tests.  Thanks.

**Comment by saghul** [comment]
All tests have been fixed and Python 3.8 is now also in the test matrix.
