### ISSUE TITLE
Publish wheels for python 3.8

### ISSUE THREAD

**Issue by derek-miller** [saghul/pycares#110]
Getting this package to build on macOS proves to be very difficult. It would be nice to have wheels built for python 3.8.

**Comment by saghul** [comment]
I have plans to do that once I can find some time for it. Sorry about that.

**Comment by derek-miller** [comment]
If there is anything I can do to help let me know.

**Comment by saghul** [comment]
Pycares 3.1.0 is now availablw with wheels also for Python 3.8: https://pypi.org/project/pycares/3.1.0/#files
