### ISSUE TITLE
Test failure with python3.8

### ISSUE THREAD

**Issue by kitterma** [saghul/pycares#117]
I'm now getting this test failure with 3.1.0 with python3.8:

======================================================================
FAIL: test_idna_encoding (__main__.DNSTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/tests.py", line 434, in test_idna_encoding
    self.assertEqual(self.errorno, pycares.errno.ARES_ENOTFOUND)
AssertionError: 11 != 4

Any suggestions?  Maybe I'm missing something?  python3-idna is installed.

**Comment by saghul** [comment]
It’s possible your resolver tries to be “helpful” and does something to avoid the failure. As you can see in the CI build history tests are passing just fine.

This is not a problem with pycares but with your environment I think.

**Comment by saghul** [comment]
No follow-up, closing.
