### ISSUE TITLE
It's exciting that the c-ares library supports TTL!

### ISSUE THREAD

**Issue by shmilylty** [saghul/pycares#123]
For details, please see https://github.com/c-ares/c-ares/pull/257
Is it possible to consider not allowing pycares to bring its own c-ares library now?
@saghul

**Comment by saghul** [comment]
Sure thing! But did they add support for it for all lookup types or just getadddrinfo? At any rate, a PR would be most welcome!

**Comment by saghul** [comment]
pycares 4.0.0 is out and I dropped out-of-tree patches. We now have TTL support wherever upstream has it. https://github.com/saghul/pycares/releases/tag/pycares-4.0.0
