### ISSUE TITLE
Compile errors when installing on Python 3.9.1 on macOS

### ISSUE THREAD

**Issue by jml** [saghul/pycares#136]
Hi!

I'm trying to install pycares on Python 3.9.1 on macOS 11.1. It errors out (see attached log). 

I don't think this happens on Linux, because it builds fine in our Docker images.

[pycares-install-log.txt](https://github.com/saghul/pycares/files/5862459/pycares-install-log.txt)

**Comment by 0xHJK** [comment]
I have the same problem

**Comment by 0xHJK** [comment]
try `pip install wheel`

**Comment by jml** [comment]
Same. 

[pycares-install-log-wheel.txt](https://github.com/saghul/pycares/files/5911294/pycares-install-log-wheel.txt)

**Comment by erikcw** [comment]
Also running into the same issue.

**Comment by hynek** [comment]
See #139 y'all

**Comment by jml** [comment]
Here's how I worked around this:

```
brew uninstall --ignore-dependencies c-ares
pip install pycares
brew install c-ares
```

YMMV.

**Comment by fernandofleury** [comment]
@jml That unfortunately didn't do the trick for me. I have the "exact" log error. But maybe I have `c-ares` installed differently?

**Comment by ibexnet** [comment]
Anyone has fix the issue?
I have the same problem under OSX 10.14 with python 3.9.4 (pip 21.0.1).
I already tried to uninstall c-ares via brew but the problem still the same.

I have installed pycares under python2 but I need on python3 and I can't find a solution. 
Please somebody has any suggestions?

**Comment by kigawas** [comment]
> Anyone has fix the issue?
> I have the same problem under OSX 10.14 with python 3.9.4 (pip 21.0.1).
> I already tried to uninstall c-ares via brew but the problem still the same.
> 
> I have installed pycares under python2 but I need on python3 and I can't find a solution.
> Please somebody has any suggestions?

See my patch on #141

**Comment by ibexnet** [comment]
thanks a lot! you save my time

**Comment by johnthagen** [comment]
In my case, we had pinned `pycares==3.1.1`, which doesn't have a Python 3.9 wheel. Updating our pinned version to 4.0.0 fixed the issue.

**Comment by SpenTappy** [comment]
Thank you @johnthagen!  This solved it for me. 3.1.1 was for Python 3.8.
