### ISSUE TITLE
Missing user data in callbacks

### ISSUE THREAD

**Issue by sergico** [saghul/pycares#137]
More than an issue this is a question.
- Is there a way to pass some custom data to a request and get it back in the callback, the same way it works for the original C based lib c-ares?
- I'm trying to implement multiple dns requests and it would be really useful to have a way to recollect requests and responses unless there is already some mechanics in place that I'm not understanding from the documentation

As an exemple:
```
void ares_gethostbyname(ares_channel channel, const char *name,
int family, ares_host_callback callback, void *arg)
```

**Comment by saghul** [comment]
You can use a partial function for that: https://docs.python.org/3.8/library/functools.html#functools.partial
