### ISSUE TITLE
4.0.0 Q: how to build pycares against system installed c-ares ?

### ISSUE THREAD

**Issue by kloczek** [saghul/pycares#154]
Looks like in 4.0.0 in deps/c-ares  is bundled c-ares and by default `build` is trying to compile pycares using that code.
Q: Is it any/easy way to build pycares against already installed shared c-ares?

**Comment by saghul** [comment]
The default is still to use the embedded build.

This is explained in the README, you can set the PYCARES_USE_SYSTEM_LIB env variable when building and the system library will be used.

**Comment by kloczek** [comment]
It works :)
Thank you.
