### ISSUE TITLE
3.11 wheels

### ISSUE THREAD

**Issue by ChrisLovering** [saghul/pycares#175]
I see the most recent [commit](https://github.com/saghul/pycares/commit/06d1ecdd57d4da4ddbe751463c576dcaf0f3baf8) updated CI build 3.11 wheels.

Is a new release planned to be made to trigger CI to run in order for these wheels to be built and pushed to pypi?

**Comment by saghul** [comment]
Hey there! Sure, I'll try to kick off a release soon.

**Comment by saghul** [comment]
4.3.0 is out!
