### ISSUE TITLE
Invalid unicode in author email field of README.rst

### ISSUE THREAD

**Issue by zerosignal0** [saghul/pycares#18]
Python 3.4.x is unable to build / install the latest version of this library due to incompatiable unicode used in the authors name/email field.  Removal of this line or usage of conversion tools such as iconv fix the issue.

Here is a repro from my environment:

docker container: running ubuntu 14.04 
docker host: ubuntu 14.04
env vars: no custom env vars, all locale settings default
python: 3.4.3 built from source with no additional flags
pip install of pycares 0.6.3

Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    long_description = open("README.rst").read(),
  File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1428: ordinal not in range(128)

The same can be seen if attempted to build from source.  

Running the following on the source copy will fix the issue:

iconv -c -f utf-8 -t ascii README.rst > README.rst.new
mv README.rst.new README.rst
python3 setup.py install

**Comment by saghul** [comment]
What error do you get? What version are you using? That's supposed to be handled by https://github.com/saghul/pycares/commit/ecb5062c31aae66c655c1526ccf21ee0c944d414

**Comment by zerosignal0** [comment]
Hello,

Sorry about the missing details, I guess my copy paste failed a bit.  Anyways I have edited my original comment above.

regards,
Gary

**Comment by saghul** [comment]
Version 0.6.3 does not include the fix I mentioned, look at the line which fails, it's not the one in master. You'll need to pull master instead. I'll make a release with the fix soon.

**Comment by saghul** [comment]
I just released version 0.7.0, which includes the fix.
