### ISSUE TITLE
UTF8 encoding problem

### ISSUE THREAD

**Issue by gvanem** [saghul/pycares#19]
While trying to use Python3 to build `pycares.pyd`, I get:
```
F:\MingW32\src\inet\DNS\c-ares\PyCares>python3 setup.py build
  File "setup.py", line 1
SyntaxError: encoding problem: utf8
```

What could be the reason for this? 

I have no problem with Python2. But just moving that line 2 lines further down fixes it:
```
--- a/setup.py    2015-08-18 15:54:48
+++ b/setup.py 2015-08-18 15:26:35
@@ -1,5 +1,3 @@
-
-
 # coding=utf8

 from distutils.core import setup, Extension
```

**Comment by saghul** [comment]
What locale are you using?

I think moving it "solves" it because it's actually ignored, but that's not a proper fix...

**Comment by gvanem** [comment]
> What locale are you using?

You mean my active code-page or something? In my Windows 8.1 shell (4NT Unicode) I have "**Active code page: 865**" if that is relevant.

**Comment by saghul** [comment]
What error do you get if you modify the coding line and replace "utf8" with "utf-8" (no quotes)?

**Comment by gvanem** [comment]
That was it! Python3 needs `# coding=utf-8`.

**Comment by saghul** [comment]
Thanks for confirming! I'll fix it in this and other projects :-)
