### ISSUE TITLE
is pypy + gevent supported?

### ISSUE THREAD

**Issue by thestick613** [saghul/pycares#21]
The following code, adopted from https://github.com/slimta/python-slimta/blob/master/slimta/util/dns.py
works well on all platforms except pypy + gevent. The result is actually very strange; the process is blocked on `cls._channel.process_fd(fd, pycares.ARES_SOCKET_BAD)` and refuses to exit, except when sent a `kill -9`.

    from __future__ import absolute_import
    from functools import partial
    
    import pycares
    import pycares.errno
    import gevent
    from gevent import select, sleep
    from gevent.event import AsyncResult
    
    class DNSResolver(object):
        channel = None
        _channel = None
        _thread = None
    
        @classmethod
        def query(cls, name, query_type):
            result = AsyncResult()
            query_type = cls._get_query_type(query_type)
            cls._channel = cls._channel or cls.channel or pycares.Channel()
            cls._channel.query(name, query_type, partial(cls._result_cb, result))
            cls._thread = cls._thread or gevent.spawn(cls._wait_channel)
            return result
    
        @classmethod
        def _get_query_type(cls, query_type):
            if isinstance(query_type, str):
                type_attr = 'QUERY_TYPE_{0}'.format(query_type.upper())
                return getattr(pycares, type_attr)
            return query_type
    
        @classmethod
        def _result_cb(cls, result, answer, errno):
            if errno:
                result.set_exception(errno)
            else:
                result.set(answer)
    
        @classmethod
        def _wait_channel(cls):
            try:
                while True:
                    read_fds, write_fds = cls._channel.getsock()
                    if not read_fds and not write_fds:
                        break
                    timeout = cls._channel.timeout()
                    if not timeout:
                        cls._channel.process_fd(pycares.ARES_SOCKET_BAD,
                                                pycares.ARES_SOCKET_BAD)
                        continue
                    rlist, wlist, xlist = select.select(
                        read_fds, write_fds, [], timeout)
                    for fd in rlist:
                        cls._channel.process_fd(fd, pycares.ARES_SOCKET_BAD)
                    for fd in wlist:
                        cls._channel.process_fd(pycares.ARES_SOCKET_BAD, fd)
            except Exception:
                log_exception(__name__)
                cls._channel.cancel()
                cls._channel = None
                raise
            finally:
                cls._thread = None
    
    answer = DNSResolver.query("gmail.com", 'MX').get()
    print answer

**Comment by saghul** [comment]
I have not tested pycares with PyPy. Generally speaking, Python modules written in C tend to do poorly in PyPy due to the emulation layer, but I haven't checked if this is the case.

What you can do first is see if the test suite passes on PyPy, that way it's easier to know where the problem comes from.

**Comment by thestick613** [comment]
pypy tests.py 
    test_channel_destroyed (__main__.DNSTest) ... ok
    test_channel_timeout (__main__.DNSTest) ... ok
    test_gethostbyaddr (__main__.DNSTest) ... ok
    test_gethostbyaddr6 (__main__.DNSTest) ... ok
    test_gethostbyname (__main__.DNSTest) ... ok
    test_gethostbyname_small_timeout (__main__.DNSTest) ... ok
    test_getnameinfo (__main__.DNSTest) ... ok
    test_query_a (__main__.DNSTest) ... ok
    test_query_a_bad (__main__.DNSTest) ... ok
    test_query_a_rotate (__main__.DNSTest) ... ok
    test_query_aaaa (__main__.DNSTest) ... ok
    test_query_bad_type (__main__.DNSTest) ... ok
    test_query_cancelled (__main__.DNSTest) ... ok
    test_query_cname (__main__.DNSTest) ... ok
    test_query_mx (__main__.DNSTest) ... ok
    test_query_naptr (__main__.DNSTest) ... ok
    test_query_ns (__main__.DNSTest) ... ok
    test_query_ptr (__main__.DNSTest) ... ok
    test_query_ptr_ipv6 (__main__.DNSTest) ... ok
    test_query_soa (__main__.DNSTest) ... ok
    test_query_srv (__main__.DNSTest) ... ok
    test_query_timeout (__main__.DNSTest) ... ok
    test_query_txt (__main__.DNSTest) ... ok
    test_reverse_address (__main__.DNSTest) ... ok
    
    ----------------------------------------------------------------------
    Ran 24 tests in 2.422s
    
    OK

Tests look okay. pypy has gotten VERY matture over the last 2 years, and i've been throwing a lot of modules at it.

**Comment by saghul** [comment]
I gave a quick test and the test suite passes on PyPy so I guess it must be a problem with the Gevent side of things.

**Comment by saghul** [comment]
> Tests look okay. pypy has gotten VERY matture over the last 2 years, and i've been throwing a lot of modules at it.

Oh, didn't see your reply coming before I wrote mine, sorry.

**Comment by thestick613** [comment]
Thanks, i'll post this to gevent issue tracker as well!

**Comment by saghul** [comment]
Closing since there is nothing actionable from pycares' perspective. Holler is you find an actual bug on pycares.
