### ISSUE TITLE
double free or corruption (!prev) bug

### ISSUE THREAD

**Issue by brizzbane** [saghul/pycares#26]
Created by request from https://github.com/saghul/pyuv/issues/214.

To your question in that thread:

> saghul 
Seems to be a pycares issue, can you please open the issue there? The problem seems to be caused by parsing the answer, can you please tell me what domain you're trying to resolve?

Is there a way that I can figure out the domain that crashes it...besides just systematically narrowing down the domains that don't?

Right now I'm just processing a large list of email addresses for many different domains.

**Comment by saghul** [comment]
> Is there a way that I can figure out the domain that crashes it...besides just systematically narrowing down the domains that don't?
> 
> Right now I'm just processing a large list of email addresses for many different domains.

I'm afraid you'll have to "bisect" the list, since the crash happens in processing, which is triggered for more than one query at once.

**Comment by brizzbane** [comment]
Ok, will report back! Thanks.

**Comment by brizzbane** [comment]
I'm having trouble.  I get to a super small list of domains.  It crashes as expected.  Then I double check before I post list here--and it doesn't crash on that list anymore.

Is it possible pycares is 'caching' the results of the crash or something?

**Comment by saghul** [comment]
Nope, there is no caching. If you run the script multiple times, does it
crash?

**Comment by brizzbane** [comment]
When I get it narrowed down to like 8 domains.  It will crash ~2 times, and then when I run it a third time, it won't (for that set of domains).

**Comment by saghul** [comment]
Doh. Can you send me the list of domains and the test program? (feel free to email if you don't want to post it here)

**Comment by brizzbane** [comment]
So I'm working on putting together a self contained example..  It's not crashing when I don't have my custom client do something on the pycares callback. (i.e. only resolve mx records)

I'll figure it out.  May have to email you some parts of it.

**Comment by brizzbane** [comment]
Have done more testing inside of gdb, see this on every crash thus far:

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff3a6d63f in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4

**Comment by brizzbane** [comment]
this backtrace is from the longest runinng instance I've had my client going (by disabling most SSL things):

> #0  0x00007ffff396d63f in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#1  0x00007ffff396d814 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#2  0x00007ffff396d1ae in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#3  0x00007ffff394b1db in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#4  0x00007ffff395bd76 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#5  0x00007ffff395c6c3 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#6  0x00007ffff395c867 in curl_multi_socket_action () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#7  0x00007ffff3bacd6c in ?? () from /usr/lib/python2.7/dist-packages/pycurl.x86_64-linux-gnu.so
#8  0x00000000004bbc2a in call_function (oparg=<optimized out>, pp_stack=0x7fffffffd420) at ../Python/ceval.c:4350
#9  PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#10 0x00000000004b9416 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#11 0x00000000004d5269 in function_call.lto_priv () at ../Objects/funcobject.c:526
#12 0x00000000004edbce in PyObject_Call (kw=0x0, arg=0x7ffff0276638, func=0x7ffff3e4b050) at ../Objects/abstract.c:2546
#13 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602
#14 0x00000000004aefc3 in PyObject_Call (kw=0x0, arg=0x7ffff0292d90, func=0x7ffff02b5730) at ../Objects/abstract.c:2546
#15 PyObject_CallFunctionObjArgs () at ../Objects/abstract.c:2773
#16 0x00007ffff6b23ad0 in pyuv__timer_cb (handle=0x7ffff3dc2ae8) at src/timer.c:15
#17 0x00007ffff6b4bc16 in uv__run_timers (loop=0x7ffff6d69180 <default_loop_struct>) at src/unix/timer.c:165
#18 0x00007ffff6b3bbef in uv_run (loop=0x7ffff6d69180 <default_loop_struct>, mode=UV_RUN_ONCE) at src/unix/core.c:355
#19 0x00007ffff6b2ecb8 in Loop_func_run (self=0xe90a60, args=<optimized out>) at src/loop.c:62
#20 0x00000000004bbc2a in call_function (oparg=<optimized out>, pp_stack=0x7fffffffda90) at ../Python/ceval.c:4350
#21 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#22 0x00000000004b9416 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#23 0x00000000004c16f3 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffffffdc90, func=0x7ffff3e4e578)
    at ../Python/ceval.c:4446
#24 call_function (oparg=<optimized out>, pp_stack=0x7fffffffdc90) at ../Python/ceval.c:4371
#25 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#26 0x00000000004b9416 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#27 0x00000000004e9f4f in PyEval_EvalCode (locals=0x7ffff7f63168, globals=0x7ffff7f63168, co=0x7ffff7e7da30)
    at ../Python/ceval.c:669
#28 run_mod.lto_priv () at ../Python/pythonrun.c:1370
---Type <return> to continue, or q <return> to quit---
#29 0x00000000004e4b42 in PyRun_FileExFlags () at ../Python/pythonrun.c:1356
#30 0x00000000004e3406 in PyRun_SimpleFileExFlags () at ../Python/pythonrun.c:948
#31 0x0000000000492de3 in Py_Main () at ../Modules/main.c:640
#32 0x00007ffff6f13870 in __libc_start_main (main=0x492830 <main>, argc=2, argv=0x7fffffffe0d8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe0c8) at libc-start.c:291
#33 0x0000000000492759 in _start ()

**Comment by saghul** [comment]
The crash happens in a call to libcurl. I suggest you simplify your script to the bare minimum, and add compnents until it blows up, otherwise it's going to be tricky to narrow it down.

**Comment by brizzbane** [comment]
I'm going to be straightforward w/what I'm doing.  

I'm connecting to/through open proxies, so the proxy servers behind each IP address varies considerably. 

I've removed all variables that I could think of besides changing the proxy I connect to.  To debug, I wrote the proxy I was connecting to before making the request. When it crashed-, checked the last line in the file to see what the proxy was, and made a comment next to it.

This worked.  Ended up with two ip:ports that consistently crashed.  The backtrace is also the same w/each crash.

If this is something you can help with, I will send you the client and IP addresses/ports it crashed on via email.

**Comment by saghul** [comment]
It's very hard to tell. The issue you initially opened was a crash in c-ares, maybe because you called some function which is not allowed to run in a callback, like changing the nameservers. Now you get a crash in libgnutls, ...

I suggest you start replacing the components until you find the culprit. I know it's hard, but without a reliable way of reproducing the issue I can't really tell if there is a bug and in which library :-)

**Comment by brizzbane** [comment]
sending you an email now.  will include a zip file with the files, and also made you can account on my server, so you can just log in and run it (if you prefer).  If you go that route, and need me to install anything as root, let me know!

so much appreciate your help.

**Comment by brizzbane** [comment]
The IP/port combo in the code that I gave you is no longer valid.  If you are OK w/using the account I created on my server, I'll make sure it always has one that crashes..

**Comment by saghul** [comment]
Will do, but it'll take me a few days to find the time.

**Comment by brizzbane** [comment]
Just curious, got your response in email.  

From your experience debugging things.. Is it possible (or likely?) that the issue I originally posted in the pyuv repository, and the backtrace from the program you ran on the server, are the same 'root' bug?  Originally in that thread you said that you thought that it might be because of the way pycares was parsing the response..   Then as I removed components, pycares wasn't even a factor.. 

I guess I'm asking because I wonder that if I'm able to find someone to track down this bug, if it will resolve this hard crash, or if I'm just in a giant rat's nest.

in case this is helpful to anyone in the future, this is that backtrace:

>#0  0x00007ffff5b6e63f in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#1  0x00007ffff5b6e814 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#2  0x00007ffff5b6e1ae in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#3  0x00007ffff5b4c1db in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#4  0x00007ffff5b5cd76 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#5  0x00007ffff5b5d6c3 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#6  0x00007ffff5b5d867 in curl_multi_socket_action () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#7  0x00007ffff5dadd6c in ?? () from /usr/lib/python2.7/dist-packages/pycurl.x86_64-linux-gnu.so
#8  0x00000000004beb0a in call_function (oparg=<optimized out>, pp_stack=0x7fffffffd630) at ../Python/ceval.c:4350
#9  PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#10 0x00000000004bc326 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#11 0x00000000004d7fa9 in function_call.lto_priv () at ../Objects/funcobject.c:523
#12 0x00000000004f09be in PyObject_Call (kw=0x0, arg=0x7ffff20e77e8, func=0x7ffff1ea9500) at ../Objects/abstract.c:2546
#13 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602
#14 0x00000000004b0633 in PyObject_Call (kw=0x0, arg=0x7ffff7e89cd0, func=0x7ffff1eb8820) at ../Objects/abstract.c:2546
#15 PyObject_CallFunctionObjArgs () at ../Objects/abstract.c:2773
#16 0x00007ffff6b23ad0 in pyuv__timer_cb (handle=0x7ffff1e893b0) at src/timer.c:15
#17 0x00007ffff6b4bc16 in uv__run_timers (loop=0x7ffff6d69180 <default_loop_struct>) at src/unix/timer.c:165
#18 0x00007ffff6b3bbef in uv_run (loop=0x7ffff6d69180 <default_loop_struct>, mode=UV_RUN_ONCE) at src/unix/core.c:355
#19 0x00007ffff6b2ecb8 in Loop_func_run (self=0xbed050, args=<optimized out>) at src/loop.c:62
#20 0x00000000004beb0a in call_function (oparg=<optimized out>, pp_stack=0x7fffffffdca0) at ../Python/ceval.c:4350
#21 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#22 0x00000000004bc326 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#23 0x00000000004ecf9f in PyEval_EvalCode (locals=0x7ffff7f63168, globals=0x7ffff7f63168, co=0x7ffff7e78db0)
    at ../Python/ceval.c:669
#24 run_mod.lto_priv () at ../Python/pythonrun.c:1370
#25 0x00000000004e7b72 in PyRun_FileExFlags () at ../Python/pythonrun.c:1356
#26 0x00000000004e6416 in PyRun_SimpleFileExFlags () at ../Python/pythonrun.c:948
#27 0x0000000000494a87 in Py_Main () at ../Modules/main.c:640
#28 0x00007ffff6f13870 in __libc_start_main (main=0x494490 <main>, argc=2, argv=0x7fffffffe0e8, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe0d8) at libc-start.c:291
---Type <return> to continue, or q <return> to quit---
#29 0x00000000004943b9 in _start ()

**Comment by saghul** [comment]
I don't think tehy are related. The first thing I'd recommend is that you install the -dbg versions ob gnutls and curl, so the backtrace has actual symbols, instead of the ??, and start from there.

**Comment by brizzbane** [comment]
If you don't think they are related, I can provide you w/the code (on my server again), that reproduces these backtraces.

http://

** Error in `/usr/bin/python': double free or corruption (!prev): 0x00000000033fd1f0 ***

Program received signal SIGABRT, Aborted.
0x00007ffff6f26507 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff6f26507 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6f278da in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff6f64b13 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff6f69f6e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff6f6a74b in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007ffff6702c64 in ares__free_query (query=0x33fd1f0) at src/ares_process.c:1316
#6  0x00007ffff6702b56 in end_query (channel=0x33eace0, query=0x33fd1f0, status=0, 
    abuf=0x7fffffff93a0 "|v\201\200", alen=150) at src/ares_process.c:1290
#7  0x00007ffff6701770 in process_answer (channel=0x33eace0, 
    abuf=0x7fffffff93a0 "|v\201\200", alen=150, whichserver=0, tcp=0, 
    now=0x7fffffffa3f0) at src/ares_process.c:613
#8  0x00007ffff6701300 in read_udp_packets (channel=0x33eace0, read_fds=0x0, 
    read_fd=15, now=0x7fffffffa3f0) at src/ares_process.c:478
#9  0x00007ffff6700808 in processfds (channel=0x33eace0, read_fds=0x0, read_fd=15, 
    write_fds=0x0, write_fd=-1) at src/ares_process.c:127
#10 0x00007ffff670089b in ares_process_fd (channel=0x33eace0, read_fd=15, write_fd=-1)
    at src/ares_process.c:148
#11 0x00007ffff66f6243 in Channel_func_process_fd (self=0x7fffef8d6170, 
    args=<optimized out>) at src/cares.c:1147
#12 0x00000000004beb0a in call_function (oparg=<optimized out>, 
    pp_stack=0x7fffffffa4f0) at ../Python/ceval.c:4350
#13 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#14 0x00000000004bc326 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#15 0x00000000004d7fa9 in function_call.lto_priv () at ../Objects/funcobject.c:523
#16 0x00000000004f09be in PyObject_Call (kw=0x0, arg=0x7ffff45fcec0, 
    func=0x7ffff01d42a8) at ../Objects/abstract.c:2546
#17 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602
#18 0x00000000004b0633 in PyObject_Call (kw=0x0, arg=0x7ffff01a9aa0, 
    func=0x7ffff0184d20) at ../Objects/abstract.c:2546
#19 PyObject_CallFunctionObjArgs () at ../Objects/abstract.c:2773
#20 0x00007ffff6b2371e in pyuv__poll_cb (handle=0x7ffff04202b8, status=0, 
    events=<optimized out>) at src/poll.c:26
#21 0x00007ffff6b4380c in uv__poll_io (loop=0x7ffff6d69180 <default_loop_struct>, 
    w=0x7ffff0420320, events=1) at src/unix/poll.c:49
---Type <return> to continue, or q <return> to quit---
#22 0x00007ffff6b4e9ed in uv__io_poll (loop=0x7ffff6d69180 <default_loop_struct>, 
    timeout=849) at src/unix/linux-core.c:345
#23 0x00007ffff6b3bbb9 in uv_run (loop=0x7ffff6d69180 <default_loop_struct>, 
    mode=UV_RUN_ONCE) at src/unix/core.c:341
#24 0x00007ffff6b2ecb8 in Loop_func_run (self=0xf21860, args=<optimized out>)
    at src/loop.c:62
#25 0x00000000004beb0a in call_function (oparg=<optimized out>, 
    pp_stack=0x7fffffffdc90) at ../Python/ceval.c:4350
#26 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#27 0x00000000004bc326 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#28 0x00000000004ecf9f in PyEval_EvalCode (locals=0x7ffff7f66168, 
    globals=0x7ffff7f66168, co=0x7ffff7e7a0b0) at ../Python/ceval.c:669
#29 run_mod.lto_priv () at ../Python/pythonrun.c:1370
#30 0x00000000004e7b72 in PyRun_FileExFlags () at ../Python/pythonrun.c:1356
#31 0x00000000004e6416 in PyRun_SimpleFileExFlags () at ../Python/pythonrun.c:948
#32 0x0000000000494a87 in Py_Main () at ../Modules/main.c:640
#33 0x00007ffff6f13870 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#34 0x00000000004943b9 in _start ()



smtp://


Program received signal SIGSEGV, Segmentation fault.
Curl_pp_vsendf (pp=0x33ff748, fmt=0x7ffff41c3679 "%s", args=args@entry=0x7fffffff3410)
    at pingpong.c:171
171     pingpong.c: No such file or directory.
(gdb) bt
#0  Curl_pp_vsendf (pp=0x33ff748, fmt=0x7ffff41c3679 "%s", 
    args=args@entry=0x7fffffff3410) at pingpong.c:171
#1  0x00007ffff41b0814 in Curl_pp_sendf (pp=pp@entry=0x33ff748, 
    fmt=fmt@entry=0x7ffff41c3679 "%s") at pingpong.c:252
#2  0x00007ffff41aec3c in smtp_perform_command (conn=conn@entry=0x33ff180)
    at smtp.c:529
#3  0x00007ffff41b00a0 in smtp_perform (dophase_done=0x7fffffff35ca, 
    connected=<synthetic pointer>, conn=0x33ff180) at smtp.c:1309
#4  smtp_regular_transfer (dophase_done=0x7fffffff35ca, conn=0x33ff180) at smtp.c:1439
#5  smtp_do (conn=0x33ff180, done=0x7fffffff35ca) at smtp.c:1345
#6  0x00007ffff418e1db in Curl_do (connp=connp@entry=0x32f4880, 
    done=done@entry=0x7fffffff35ca) at url.c:6299
#7  0x00007ffff419ed76 in multi_runsingle (multi=multi@entry=0x211ecf0, now=..., 
    data=data@entry=0x32f4870) at multi.c:1318
#8  0x00007ffff419f6c3 in multi_socket (multi=multi@entry=0x211ecf0, 
    checkall=checkall@entry=false, s=-1, ev_bitmask=<optimized out>, 
    running_handles=running_handles@entry=0x7fffffff36c4) at multi.c:2333
#9  0x00007ffff419f867 in curl_multi_socket_action (multi_handle=0x211ecf0, 
    s=<optimized out>, ev_bitmask=<optimized out>, 
    running_handles=running_handles@entry=0x7fffffff36c4) at multi.c:2442
#10 0x00007ffff43efd6c in do_multi_socket_action (self=0x7ffff016ad38, 
    args=<optimized out>) at src/multi.c:385
#11 0x00000000004beb0a in call_function (oparg=<optimized out>, 
    pp_stack=0x7fffffff3780) at ../Python/ceval.c:4350
#12 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#13 0x00000000004bc326 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#14 0x00000000004d7fa9 in function_call.lto_priv () at ../Objects/funcobject.c:523
#15 0x00000000004f09be in PyObject_Call (kw=0x0, arg=0x7fffefd1b2d8, 
    func=0x7ffff01c5f50) at ../Objects/abstract.c:2546
#16 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602
#17 0x00000000004b0633 in PyObject_Call (kw=0x0, arg=0x7ffff7f4ca50, 
    func=0x7fffefd8eb40) at ../Objects/abstract.c:2546
#18 PyObject_CallFunctionObjArgs () at ../Objects/abstract.c:2773
#19 0x00007ffff6b23ad0 in pyuv__timer_cb (handle=0x7ffff0aa7cf8) at src/timer.c:15
---Type <return> to continue, or q <return> to quit---
#20 0x00007ffff6b4bc16 in uv__run_timers (loop=0x7ffff6d69180 <default_loop_struct>)
    at src/unix/timer.c:165
#21 0x00007ffff6b3bbef in uv_run (loop=0x7ffff6d69180 <default_loop_struct>, 
    mode=UV_RUN_ONCE) at src/unix/core.c:355
#22 0x00007ffff6b2ecb8 in Loop_func_run (self=0xf21860, args=<optimized out>)
    at src/loop.c:62
#23 0x00000000004beb0a in call_function (oparg=<optimized out>, 
    pp_stack=0x7fffffff3df0) at ../Python/ceval.c:4350
#24 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#25 0x00000000004bc326 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#26 0x00000000004c3e1a in fast_function (nk=<optimized out>, na=<optimized out>, 
    n=<optimized out>, pp_stack=0x7fffffff3ff0, func=0x7fffef94a230)
    at ../Python/ceval.c:4445
#27 call_function (oparg=<optimized out>, pp_stack=0x7fffffff3ff0)
    at ../Python/ceval.c:4370
#28 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#29 0x00000000004bc326 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#30 0x00000000004d7fa9 in function_call.lto_priv () at ../Objects/funcobject.c:523
#31 0x00000000004b0633 in PyObject_Call (kw=0x0, arg=0x7fffefd26518, 
    func=0x7fffef94a2a8) at ../Objects/abstract.c:2546
#32 PyObject_CallFunctionObjArgs () at ../Objects/abstract.c:2773
#33 0x00007ffff66f45c1 in query_mx_cb (arg=0x7fffef94a2a8, status=<optimized out>, 
    timeouts=<optimized out>, answer_buf=<optimized out>, answer_len=<optimized out>)
    at src/cares.c:309
#34 0x00007ffff6703113 in qcallback (arg=0x3326110, status=0, timeouts=1, 
    abuf=0x7fffffff4450 "n\254\201\200", alen=150) at src/ares_query.c:183
#35 0x00007ffff6702b4a in end_query (channel=0x33eace0, query=0x33fd1f0, status=0, 
    abuf=0x7fffffff4450 "n\254\201\200", alen=150) at src/ares_process.c:1289
#36 0x00007ffff6701770 in process_answer (channel=0x33eace0, 
    abuf=0x7fffffff4450 "n\254\201\200", alen=150, whichserver=1, tcp=0, 
    now=0x7fffffff54a0) at src/ares_process.c:613
#37 0x00007ffff6701300 in read_udp_packets (channel=0x33eace0, read_fds=0x0, 
    read_fd=22, now=0x7fffffff54a0) at src/ares_process.c:478
#38 0x00007ffff6700808 in processfds (channel=0x33eace0, read_fds=0x0, read_fd=22, 
---Type <return> to continue, or q <return> to quit---
    write_fds=0x0, write_fd=-1) at src/ares_process.c:127
#39 0x00007ffff670089b in ares_process_fd (channel=0x33eace0, read_fd=22, write_fd=-1)
    at src/ares_process.c:148
#40 0x00007ffff66f6243 in Channel_func_process_fd (self=0x7fffef8d6170, 
    args=<optimized out>) at src/cares.c:1147
#41 0x00000000004beb0a in call_function (oparg=<optimized out>, 
    pp_stack=0x7fffffff55a0) at ../Python/ceval.c:4350
#42 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#43 0x00000000004bc326 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#44 0x00000000004d7fa9 in function_call.lto_priv () at ../Objects/funcobject.c:523
#45 0x00000000004f09be in PyObject_Call (kw=0x0, arg=0x7fffef91eb50, 
    func=0x7ffff01d42a8) at ../Objects/abstract.c:2546
#46 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602
#47 0x00000000004b0633 in PyObject_Call (kw=0x0, arg=0x7ffff01e1780, 
    func=0x7fffef8c4dc0) at ../Objects/abstract.c:2546
#48 PyObject_CallFunctionObjArgs () at ../Objects/abstract.c:2773
#49 0x00007ffff6b2371e in pyuv__poll_cb (handle=0x7ffff04203c8, status=0, 
    events=<optimized out>) at src/poll.c:26
#50 0x00007ffff6b4380c in uv__poll_io (loop=0x7ffff6d69180 <default_loop_struct>, 
    w=0x7ffff0420430, events=1) at src/unix/poll.c:49
#51 0x00007ffff6b4e9ed in uv__io_poll (loop=0x7ffff6d69180 <default_loop_struct>, 
    timeout=1000) at src/unix/linux-core.c:345
#52 0x00007ffff6b3bbb9 in uv_run (loop=0x7ffff6d69180 <default_loop_struct>, 
    mode=UV_RUN_ONCE) at src/unix/core.c:341
#53 0x00007ffff6b2ecb8 in Loop_func_run (self=0xf21860, args=<optimized out>)
    at src/loop.c:62
#54 0x00000000004beb0a in call_function (oparg=<optimized out>, 
    pp_stack=0x7fffffff8d40) at ../Python/ceval.c:4350
#55 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#56 0x00000000004bc326 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#57 0x00000000004c3e1a in fast_function (nk=<optimized out>, na=<optimized out>, 
    n=<optimized out>, pp_stack=0x7fffffff8f40, func=0x7fffef94a230)
    at ../Python/ceval.c:4445
#58 call_function (oparg=<optimized out>, pp_stack=0x7fffffff8f40)
---Type <return> to continue, or q <return> to quit---
    at ../Python/ceval.c:4370
#59 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#60 0x00000000004bc326 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#61 0x00000000004d7fa9 in function_call.lto_priv () at ../Objects/funcobject.c:523
#62 0x00000000004b0633 in PyObject_Call (kw=0x0, arg=0x7ffff0403fc8, 
    func=0x7fffef94a2a8) at ../Objects/abstract.c:2546
#63 PyObject_CallFunctionObjArgs () at ../Objects/abstract.c:2773
#64 0x00007ffff66f45c1 in query_mx_cb (arg=0x7fffef94a2a8, status=<optimized out>, 
    timeouts=<optimized out>, answer_buf=<optimized out>, answer_len=<optimized out>)
    at src/cares.c:309
#65 0x00007ffff6703113 in qcallback (arg=0x3326110, status=0, timeouts=0, 
    abuf=0x7fffffff93a0 "n\254\201\200", alen=150) at src/ares_query.c:183
#66 0x00007ffff6702b4a in end_query (channel=0x33eace0, query=0x33fd1f0, status=0, 
    abuf=0x7fffffff93a0 "n\254\201\200", alen=150) at src/ares_process.c:1289
#67 0x00007ffff6701770 in process_answer (channel=0x33eace0, 
    abuf=0x7fffffff93a0 "n\254\201\200", alen=150, whichserver=0, tcp=0, 
    now=0x7fffffffa3f0) at src/ares_process.c:613
#68 0x00007ffff6701300 in read_udp_packets (channel=0x33eace0, read_fds=0x0, 
    read_fd=15, now=0x7fffffffa3f0) at src/ares_process.c:478
#69 0x00007ffff6700808 in processfds (channel=0x33eace0, read_fds=0x0, read_fd=15, 
    write_fds=0x0, write_fd=-1) at src/ares_process.c:127
#70 0x00007ffff670089b in ares_process_fd (channel=0x33eace0, read_fd=15, write_fd=-1)
    at src/ares_process.c:148
#71 0x00007ffff66f6243 in Channel_func_process_fd (self=0x7fffef8d6170, 
    args=<optimized out>) at src/cares.c:1147
#72 0x00000000004beb0a in call_function (oparg=<optimized out>, 
    pp_stack=0x7fffffffa4f0) at ../Python/ceval.c:4350
#73 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#74 0x00000000004bc326 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#75 0x00000000004d7fa9 in function_call.lto_priv () at ../Objects/funcobject.c:523
#76 0x00000000004f09be in PyObject_Call (kw=0x0, arg=0x7ffff45fcec0, 
    func=0x7ffff01d42a8) at ../Objects/abstract.c:2546
#77 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602
#78 0x00000000004b0633 in PyObject_Call (kw=0x0, arg=0x7ffff01a9aa0, 
---Type <return> to continue, or q <return> to quit---
    func=0x7ffff0184d20) at ../Objects/abstract.c:2546
#79 PyObject_CallFunctionObjArgs () at ../Objects/abstract.c:2773
#80 0x00007ffff6b2371e in pyuv__poll_cb (handle=0x7ffff04202b8, status=0, 
    events=<optimized out>) at src/poll.c:26
#81 0x00007ffff6b4380c in uv__poll_io (loop=0x7ffff6d69180 <default_loop_struct>, 
    w=0x7ffff0420320, events=1) at src/unix/poll.c:49
#82 0x00007ffff6b4e9ed in uv__io_poll (loop=0x7ffff6d69180 <default_loop_struct>, 
    timeout=851) at src/unix/linux-core.c:345
#83 0x00007ffff6b3bbb9 in uv_run (loop=0x7ffff6d69180 <default_loop_struct>, 
    mode=UV_RUN_ONCE) at src/unix/core.c:341
#84 0x00007ffff6b2ecb8 in Loop_func_run (self=0xf21860, args=<optimized out>)
    at src/loop.c:62
#85 0x00000000004beb0a in call_function (oparg=<optimized out>, 
    pp_stack=0x7fffffffdc90) at ../Python/ceval.c:4350
#86 PyEval_EvalFrameEx () at ../Python/ceval.c:2987
#87 0x00000000004bc326 in PyEval_EvalCodeEx () at ../Python/ceval.c:3582
#88 0x00000000004ecf9f in PyEval_EvalCode (locals=0x7ffff7f66168, 
    globals=0x7ffff7f66168, co=0x7ffff7e7a0b0) at ../Python/ceval.c:669
#89 run_mod.lto_priv () at ../Python/pythonrun.c:1370
#90 0x00000000004e7b72 in PyRun_FileExFlags () at ../Python/pythonrun.c:1356
#91 0x00000000004e6416 in PyRun_SimpleFileExFlags () at ../Python/pythonrun.c:948
#92 0x0000000000494a87 in Py_Main () at ../Modules/main.c:640
#93 0x00007ffff6f13870 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#94 0x00000000004943b9 in _start ()

I started looking at apt-cache to try and find packages to replace the ??, think I was successful, except for:  
    #2  0x00007ffff6f64b13 in ?? () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by saghul** [comment]
No follow-up, closing. If you manage to reliably reproduce it, holler and I'll reopen.
