### ISSUE TITLE
Update c-ares to 1.11

### ISSUE THREAD

**Issue by saghul** [saghul/pycares#27]

**Comment by VSSRS** [comment]
Is this in progress? Do you want me to "paste" the new c-ares source in a pull request?
Thanks.

**Comment by saghul** [comment]
I was planning to work on it as soon as I could, but if you feel like sending a PR that would be welcome. Note that the tree is slightly modified.

**Comment by VSSRS** [comment]
Are you talking about [this](https://github.com/saghul/pycares/commit/8d4783d1a4272cf96d300428bd2da7e7445c12ad) modification in particular? Or is there anything we should take into account?

**Comment by saghul** [comment]
It's a bit more than that, the source structure was also modified and custom makefiles are used, that will need re-testing.

**Comment by VSSRS** [comment]
Unfortunately, I haven't found the time to look at the custom makefiles and such. Any other updates on this issue?

Thanks.

**Comment by saghul** [comment]
Nope, sorry, I'm also short on time lately :-S

**Comment by saghul** [comment]
Done in https://github.com/saghul/pycares/commit/1178f984796ac1fc15ebdb59bb3e285e814ee18f and now part of pycares 2.0.0.

**Comment by VSSRS** [comment]
Thanks!
