### ISSUE TITLE
cffi port

### ISSUE THREAD

**Issue by boytm** [saghul/pycares#28]
I have create a cffi port of pycares due to pypy 5.0.1 cpyext cannot work with pycares . Code should be merged into pycares or leave it as a seperate project pycares.cffi ?  https://github.com/boytm/pycares

**Comment by saghul** [comment]
Wow, great work! Yes, I would like to integrate it, of course! I think we should do as follows:

- Have the main pycares module, and then a _core and _cfficore modules
- By default build the cffi core on PyPy, and the regular one elsewhere
- If an env var is set or an option is passed to setup.py, we could build the cffi version too on CPython

How does it sound? If this something you'd like to work on? If so, feel free to send a Pull Request when you are ready for review!

**Comment by boytm** [comment]
Does _cfficore dpends on _core, or  _cfficore contain C cares library iteself ?  Use simple python __init__.py to wrap standard _core module?

**Comment by saghul** [comment]
So, I think _core would be the current pycares, that is, embedding c-ares. Then _cfficore would be what you wrote, and in `__init__.py` we'd try-import one or the other.

**Comment by boytm** [comment]
On python, should build two or only build one? If only build one, I think no need to rename current pycares.pyd to \_core.pyd .
If build both on python , should usage cffi version like below ?
`import pycares.cffi as pycares`
And normal usage is
`import pycares`

**Comment by saghul** [comment]
We would build one or the other, depending on the environment. The reason to use _core and _cfficore is so users can import pycares and not care about it.

Here is a similar approach: https://github.com/saghul/python-fibers in one case I use a C extension, on the other a PyPy builtin.

**Comment by saghul** [comment]
Done in #29.

**Comment by thestick613** [comment]
This doesn't work as expected. I get this error for pip install pycares from a pypy virtualenv:
```
      File "/usr/lib/pypy/lib_pypy/cffi/setuptools_ext.py", line 128, in run
        ext.sources[0] = make_mod(self.build_temp, pre_run)
      File "/usr/lib/pypy/lib_pypy/cffi/setuptools_ext.py", line 114, in make_mod
        updated = recompiler.make_c_source(ffi, module_name, source, c_file)
      File "/usr/lib/pypy/lib_pypy/cffi/recompiler.py", line 1365, in make_c_source
        verbose)
      File "/usr/lib/pypy/lib_pypy/cffi/recompiler.py", line 1340, in _make_c_or_py_source
        recompiler.collect_step_tables()
      File "/usr/lib/pypy/lib_pypy/cffi/recompiler.py", line 233, in collect_step_tables
        self._generate("ctx")
      File "/usr/lib/pypy/lib_pypy/cffi/recompiler.py", line 218, in _generate
        method(tp, realname)
      File "/usr/lib/pypy/lib_pypy/cffi/recompiler.py", line 962, in _generate_cpy_struct_ctx
        self._struct_ctx(tp, *self._struct_names(tp))
      File "/usr/lib/pypy/lib_pypy/cffi/recompiler.py", line 866, in _struct_ctx
        "field '%s.%s'" % (tp.name, fldname))
      File "/usr/lib/pypy/lib_pypy/cffi/recompiler.py", line 921, in _check_not_opaque
        "%s is of an opaque type (not declared in cdef())" % location)
    TypeError: struct sockaddr_in6: field 'sockaddr_in6.sin6_addr' is of an opaque type (not declared in cdef())
    Complete output from command /root/venv_smtpout_pypy30/bin/pypy -c "import setuptools, tokenize;__file__='/root/venv_smtpout_pypy30/build/pycares/setup.py';exec(compile(getattr(tokenize, 'open',:
    running install
```

I don't get this when i'm running [boytm's fork from github](https://github.com/boytm/pycares).

**Comment by saghul** [comment]
Can you please open a new issue? Please mention what platform you're running, since the CFFI port works fine in the CI, but might still need some tweaking.  Thanks!
