### ISSUE TITLE
Errno Import errors

### ISSUE THREAD

**Issue by bcaudell95** [saghul/pycares#30]
Using Python3.5, importing version 2.0.0 of pycares causes import errors with error.py in future module imports.  Specifically, python seems to override the global "error.py" with the pycares file of the same name, causing future import errors.

**Comment by saghul** [comment]
Can you provide a small test I could run?

**Comment by socketubs** [comment]
@saghul Its more about applications that does `import pycares.errno`.

```python
from pycares.errno import ARES_ENOTFOUND
Import Error: No module named 'pycares.errno'
```

Which was possible with `pycares==1.0.0`.

**Comment by saghul** [comment]
Got it. I could reproduce it locally. I'll make a fix ASAP.

**Comment by socketubs** [comment]
@saghul Perfect :+1:

**Comment by saghul** [comment]
This branch should do: https://github.com/saghul/pycares/tree/errno-submodule It passes tests on Travis, I'll make a release tonight.
