### ISSUE TITLE
Documentation does not build

### ISSUE THREAD

**Issue by ortolot** [saghul/pycares#33]
Hello,

While packaging pycares for Debian, I noticed that the documentation does not build. The reason is that the docs/conf.py looks for the version number in setup.py, which fails as it is in fact in pycares/_version.py.

Here is a patch that fixes that. I had to rename it with .txt as GitHub does not accept patches (!), but I will also provide a repository to git pull from it you prefer.

[fix-doc-build.txt](https://github.com/saghul/pycares/files/438858/fix-doc-build.txt)

**Comment by saghul** [comment]
@ortolot Thanks! Mind sending it as a Pull Request? Also, I'm a Debian user myself, so I'm happy to see this happening, let me know if there is anything I can do to help.

**Comment by ortolot** [comment]
That will not be a GitHub pull request, sorry, just a message here asking you to run a git pull command I will provide. It should not be much more effort though.

**Comment by ortolot** [comment]
Here, I have just published that to my personal repository, you can pull it with either:

$ git pull git://git.ortolo.eu/pkg-pycares.git contrib/fix-doc-build
$ git pull http://git.ortolo.eu/git/pkg-pycares.git contrib/fix-doc-build

(If you want to review it first, you can create a new branch, then do this git pull, review the changes as you like, then checkout your master branch and merge the new branch in it.)

**Comment by saghul** [comment]
Landed in 8cfce1c with a slightly modified commit message, thanks!

**Comment by saghul** [comment]
I'll make a new release soon, so you can package that.

**Comment by ortolot** [comment]
Saúl Ibarra Corretgé, 2016-08-26 02:53-0700:
>I'll make a new release soon, so you can package that.

As you like, but no hurry here, e.g. if you plan to make other 
modifications, as I already integrate my fix as a patch for now.

By the way, glad you like the idea of having pycares in Debian, FYI I 
will also package aiodns, and then Poezio <http://poez.io/> which is a 
Irssi-like XMPP client that uses all that (but maybe you already know 
it).

**Comment by saghul** [comment]
> As you like, but no hurry here, e.g. if you plan to make other modifications, as I already integrate my fix as a patch for now.

There are a couple fixes already, so I might as well make one :-)

> By the way, glad you like the idea of having pycares in Debian, FYI I will also package aiodns, and then Poezio <http://poez.io/> which is a Irssi-like XMPP client that uses all that (but maybe you already know it).

Excellent! I use poezio myself!
