### ISSUE TITLE
Does not build on Mac

### ISSUE THREAD

**Issue by CaledoniaProject** [saghul/pycares#35]
I'm trying to compile pycares 2.1.0 on Mac, pip3 install fails and so does the build_inplace script,
Both resulting in an error like this,

```
src/cares.c:302:72: error: no member named 'ttl' in 'struct ares_mx_reply'
        PyStructSequence_SET_ITEM(tmp, 2, PyInt_FromLong((long)mx_ptr->ttl));
```

![screen 2016-09-27 at 17 09 38 1](https://cloud.githubusercontent.com/assets/1357701/18869297/45c18c08-84de-11e6-8fe8-7b4ee3c91fbf.jpg)

**Comment by saghul** [comment]
Do you have c-ares installed from Homebrew?  Does it go away if you remove it before installing?

**Comment by CaledoniaProject** [comment]
Right, removing `c-ares` works for me

**Comment by mtasic85** [comment]
I cannot believe that this was the issue in 2021. Great catch @CaledoniaProject ! Your instructions worked for me.

```
brew remove c-ares --ignore-dependencies
```
