### ISSUE TITLE
more kwargs?

### ISSUE THREAD

**Issue by wumpus** [saghul/pycares#39]
I'm using aiohttp which uses aiodns which uses pycares, and I'd like to use multiple source IP addresses. If I was using pycares directly I'd call pycares.channel.set_local_ip(), but, from aiohttp the easiest way for me to configure pycares.Channel is via kwargs, which get passed through.

According to your docs, most pycares.Channel options can be set by kwargs, but it appears that local_ip() and local_dev() are the exceptions. Are you open to a patch?

**Comment by saghul** [comment]
Hi there!  Glad to hear you are using aiodns and pycares :-) Sure, such a patch would be welcome.

**Comment by wumpus** [comment]
The patch is easy, but I am not having much luck installing and testing it. (I'm relatively new to python and python packaging.)

I modified the file pycares/_cfficore/__init__.py to have "class Channel" have the additional args.

I did "python ./setup.py install" and I can see it build c-ares and install some python code, but not including pycares/_cfficore

And when I "python tests/tests.py", it's clear that my code change to cfficore is not installed. Obviously the old one is installed somewhere, because the old tests all work.

**Comment by wumpus** [comment]
[pycares.diff.txt](https://github.com/saghul/pycares/files/512163/pycares.diff.txt)

**Comment by wumpus** [comment]
untested code is in https://github.com/saghul/pycares/pull/40

**Comment by saghul** [comment]
The PR will be built against different Python versions and operating systems, you can rely on the CI catching any mistakes :-)

**Comment by wumpus** [comment]
I understand CI. My problem is modifying cfficore/___init___.py doesn't seem to cause anything to happen... including in the CI, which couldn't possibly be screwing up installation.

**Comment by saghul** [comment]
Right.  So currently pycares is implemented kind-of twice.  In C in src/ and using CFFI in cfficore.  You need to make the change on both.

Currently all Python versions fail because it's not implemented in the C backend, and PyPy fails due to some type incompatibility.  You can check the Travis output for all the details.

**Comment by wumpus** [comment]
Thanks. That's worth a comment in the code :-) because I would never have figured that out from reading the Travis output!

**Comment by wumpus** [comment]
I am in an argument with ffi about the alignment of "struct in_addr *". As you can see from https://github.com/saghul/pycares/pull/42 this problem was started by your change for issue 36 https://github.com/saghul/pycares/issues/36, which fails if there's a test that calls channel.set_local_ip().

I tried adding '...' and it didn't work, so I aligned struct in_addr like Linux does (uint32_t) and that works for both Linux and Windoze. Needless to say I'm a bit uncomfortable with this "solution", as an ffi newbie...

**Comment by saghul** [comment]
Yeah, I'll add a note on the README at least.

**Comment by wumpus** [comment]
I have 2 pullreqs ready to merge, we've discussed them, they languish. Do you not get notifications for pullreq discussion?
