### ISSUE TITLE
error: implicit declaration of function 'clock_gettime' is invalid in C99

### ISSUE THREAD

**Issue by cyclehacker** [saghul/pycares#47]
I get the following error when trying to install pycares. I'm on ubuntu 16.04 using clang 3.8, python 3.5.2

I don't know where to start with this error, any help would be much appreciated.

`Collecting pycares
  Using cached pycares-2.1.1.tar.gz
Installing collected packages: pycares
  Running setup.py install for pycares ... error
    Complete output from command /home/goldielocks/py_environments/scraper_test/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r7apa5ce/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-as4w9efo-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/goldielocks/py_environments/scraper_test/include/site/python3.5/pycares:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/pycares
    copying pycares/errno.py -> build/lib.linux-x86_64-3.5/pycares
    copying pycares/__init__.py -> build/lib.linux-x86_64-3.5/pycares
    copying pycares/_version.py -> build/lib.linux-x86_64-3.5/pycares
    running build_ext
    building 'pycares._core' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/src
    creating build/temp.linux-x86_64-3.5/deps
    creating build/temp.linux-x86_64-3.5/deps/c-ares
    creating build/temp.linux-x86_64-3.5/deps/c-ares/src
    clang -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -ggdb3 -O0 -std=c99 -Wall -Werror -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/home/goldielocks/py_environments/scraper_test/include -I/usr/include/python3.5m -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c src/pycares.c -o build/temp.linux-x86_64-3.5/src/pycares.o
    clang -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -ggdb3 -O0 -std=c99 -Wall -Werror -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/home/goldielocks/py_environments/scraper_test/include -I/usr/include/python3.5m -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c deps/c-ares/src/ares__close_sockets.c -o build/temp.linux-x86_64-3.5/deps/c-ares/src/ares__close_sockets.o
    clang -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -ggdb3 -O0 -std=c99 -Wall -Werror -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/home/goldielocks/py_environments/scraper_test/include -I/usr/include/python3.5m -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c deps/c-ares/src/ares__get_hostent.c -o build/temp.linux-x86_64-3.5/deps/c-ares/src/ares__get_hostent.o
    clang -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -ggdb3 -O0 -std=c99 -Wall -Werror -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/home/goldielocks/py_environments/scraper_test/include -I/usr/include/python3.5m -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c deps/c-ares/src/ares__read_line.c -o build/temp.linux-x86_64-3.5/deps/c-ares/src/ares__read_line.o
    clang -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -ggdb3 -O0 -std=c99 -Wall -Werror -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/home/goldielocks/py_environments/scraper_test/include -I/usr/include/python3.5m -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c deps/c-ares/src/ares__timeval.c -o build/temp.linux-x86_64-3.5/deps/c-ares/src/ares__timeval.o
    deps/c-ares/src/ares__timeval.c:48:11: error: implicit declaration of function 'clock_gettime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      if(0 == clock_gettime(CLOCK_MONOTONIC, &tsnow)) {
              ^
    deps/c-ares/src/ares__timeval.c:48:25: error: use of undeclared identifier 'CLOCK_MONOTONIC'
      if(0 == clock_gettime(CLOCK_MONOTONIC, &tsnow)) {
                            ^
    2 errors generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/home/goldielocks/py_environments/scraper_test/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r7apa5ce/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-as4w9efo-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/goldielocks/py_environments/scraper_test/include/site/python3.5/pycares" failed with error code 1 in /tmp/pip-build-r7apa5ce/pycares/
`

**Comment by saghul** [comment]
That's weird, Ubuntu 16.04 is pretty recent. What kernel do you have?

**Comment by cyclehacker** [comment]
Hi thanks for getting back to me I'm on 4.4.0-72-generic.

**Comment by cyclehacker** [comment]
If it's a problem on my system any ideas what I would need to do to resolve the issue?

**Comment by cyclehacker** [comment]
A little googling  [indicates](http://stackoverflow.com/questions/13069758/got-compile-error-when-use-clock-gettime-in-c99) using --std=gnu99 compiler flag might fix it. Where/ how would I be able to add this flag to test it?

**Comment by cyclehacker** [comment]
I managed to get pycares to install by adding the --std=gnu99 flag to setup.py, which threw up a new error regarding socklen_t of fromlen on line 463 in ares_process.c. I then modified line 413 from 'ares_socklen_t' too socklen_t and it successfully installed. I was then able to install aiodns which was the orignal purpose of installing pycares. I'm not sure what the implications are/ could be of the modifications I made and would appreciate any feedback you may have? Cheers!

**Comment by saghul** [comment]
@cyclehacker Hum, interesting!  How about you make  PR and we let the CI decide? :-)

**Comment by cyclehacker** [comment]
Not sure how to do that, happy to give it a go if you can explain what I need to do.

**Comment by saghul** [comment]
Can you try this patch?

```
diff --git a/setup_cares.py b/setup_cares.py
index 97c4cc6..4c66340 100644
--- a/setup_cares.py
+++ b/setup_cares.py
@@ -72,6 +72,7 @@ class cares_build_ext(build_ext):
             self.compiler.add_include_dir(os.path.join(self.cares_dir, 'src/config_linux'))
             self.compiler.add_library('dl')
             self.compiler.add_library('rt')
+            self.extensions[0].extra_compile_args = ['-std=gnu99']
         elif sys.platform == 'darwin':
             self.compiler.add_include_dir(os.path.join(self.cares_dir, 'src/config_darwin'))
             self.compiler.define_macro('_DARWIN_USE_64_BIT_INODE', 1)

```

**Comment by cyclehacker** [comment]
Not sure how to do that either! How would I go about executing that?

**Comment by saghul** [comment]
@cyclehacker that's a diff, you can save it to a file and use `patch` or just edit setup_cares.py and add the following line:

```
self.extensions[0].extra_compile_args = ['-std=gnu99']
```

In the context you see above (around line 72).

**Comment by cyclehacker** [comment]
OK, great - I manually updated setup_cares.py file 
Should I uninstall pycares and reinstall it now? Or just leave it alone?

**Comment by saghul** [comment]
You need to try to build it again (reinstalling is fine) if it succeeds, then we might need that flag there.

**Comment by saghul** [comment]
No follow-up, closing.
