### ISSUE TITLE
pycares.Channel's default should be None, not -1

### ISSUE THREAD

**Issue by Kentzo** [saghul/pycares#59]
It's unusual to use `-1` as a placeholder for default value. Code that wraps pycares has to either explicitly map `None` to `-1` or expose `-1` as a default value. Given that `None` is widely used, mapping is likely inevitable.

Instead, implementation should be adjusted to allow None as a "use default" placeholder along with `-1` for backward compatibility.

**Comment by saghul** [comment]
Sounds reasonable, I'd take a patch if you're up for it :-)

**Comment by saghul** [comment]
Fixed in https://github.com/saghul/pycares/pull/83
