### ISSUE TITLE
Wrong interpretation of DNS response

### ISSUE THREAD

**Issue by socketpair** [saghul/pycares#60]
Here is the place where TXT reponse starts with empty string:
https://github.com/saghul/pycares/blob/master/src/cares.c#L523

Consider the following:

```
$ dig -t TXT  no-such-domain-trash.awtomatika.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -t TXT no-such-domain-trash.awtomatika.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39390
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;no-such-domain-trash.awtomatika.com. IN	TXT

;; ANSWER SECTION:
no-such-domain-trash.awtomatika.com. 86400 IN CNAME mail.awtomatika.com.

;; Query time: 35 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Dec 06 13:09:58 +05 2017
;; MSG SIZE  rcvd: 83
```
As you can see, DNS server reponds with CNAME type instead of TXT. So, in general, pycares MUST check response type before building of response object.

The problem is that in provided case `response[0].text` will be empty string, it is inditinguishable from really empty TXT record (don't know if it is possible), and so error is not detected, but should be. This is clearly error in API design. As I think, libraries should return some error in such cases instead of empty string.

**Comment by boytm** [comment]
In your case, the return result "dns_result" is an empy list. This is just tell you "empty txt answer".

**Comment by socketpair** [comment]
NO! unfortunatelly, it returns list with one element. ant it's `.text` is empty string !

**Comment by socketpair** [comment]
Sorry for bothering you. My mistake.
