### ISSUE TITLE
Problem in pycares

### ISSUE THREAD

**Issue by erick08** [saghul/pycares#65]
I can not install the pycares

$ pip install pycares
Collecting pycares
  Using cached https://files.pythonhosted.org/packages/89/5c/3a7e1a52d6abb52b9ca1a56d2df699936e89d8b98f75cfd60d03363e7c10/pycares-2.3.0.tar.gz
Installing collected packages: pycares
  Running setup.py install for pycares ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-rbr2qc0g/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-g_igq9rt-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.6
    creating build/lib.linux-armv7l-3.6/pycares
    copying pycares/__init__.py -> build/lib.linux-armv7l-3.6/pycares
    copying pycares/__main__.py -> build/lib.linux-armv7l-3.6/pycares
    copying pycares/errno.py -> build/lib.linux-armv7l-3.6/pycares
    copying pycares/_version.py -> build/lib.linux-armv7l-3.6/pycares
    running build_ext
    building 'pycares._core' extension
    creating build/temp.linux-armv7l-3.6
    creating build/temp.linux-armv7l-3.6/src
    creating build/temp.linux-armv7l-3.6/deps
    creating build/temp.linux-armv7l-3.6/deps/c-ares
    creating build/temp.linux-armv7l-3.6/deps/c-ares/src
    arm-linux-androideabi-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/data/data/com.termux/files/usr/include/python3.6m -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c src/pycares.c -o build/temp.linux-armv7l-3.6/src/pycares.o
    In file included from src/pycares.c:2:
    src/pycares.h:7:10: fatal error: 'Python.h' file not found
    #include "Python.h"
             ^~~~~~~~~~
    1 error generated.
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-rbr2qc0g/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-g_igq9rt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-rbr2qc0g/pycares/

**Comment by erick08** [comment]
@saghul

**Comment by boytm** [comment]
you should install Python dev header and gcc on your arm device first.

**Comment by erick08** [comment]
@boytm 

How do I install dev python and gcc?

**Comment by saghul** [comment]
You seem to be running on Termux on Android. I have no idea how to get stuff installed there, sorry. I'm closing this since it's an environment issue rather than a pycares issue.
