### ISSUE TITLE
Support for multiple PTR records

### ISSUE THREAD

**Issue by econchick** [saghul/pycares#69]
Hello -

Currently, `pycares` only returns one result for a `PTR` query. However, there can be more than one result for such. Or at least, I haven't found any reference in RFCs that limit `PTR` results to one ([1034](https://tools.ietf.org/html/rfc1034), [1035](https://tools.ietf.org/html/rfc1035#section-3.3.12)) , and have found Bind [does support multiple](http://www.zytrax.com/books/dns/ch8/ptr.html). While I understand the common use case for `PTR` records is a one-to-one mapping, internally at Spotify we use it to look up [microservices](https://labs.spotify.com/2017/03/31/spotifys-lovehate-relationship-with-dns/#microservice-lookup):

### Expected
```sh
# with dig
$ dig +short -t PTR dnsresolver.roles.ash2.spotify.net
ash2-dnsresolver-a3.ash2.spotify.net.
ash2-dnsresolver-a1.ash2.spotify.net.
ash2-dnsresolver-a1926.ash2.spotify.net.
ash2-dnsresolver-a4.ash2.spotify.net.

# with adig
./adig -t PTR dnsresolver.roles.ash2.spotify.net
id: 36244
flags: qr rd ra
opcode: QUERY
rcode: NOERROR
Questions:
	dnsresolver.roles.ash2.spotify.net.		PTR
Answers:
	dnsresolver.roles.ash2.spotify.net.	300	PTR	ash2-dnsresolver-a4.ash2.spotify.net.
	dnsresolver.roles.ash2.spotify.net.	300	PTR	ash2-dnsresolver-a1.ash2.spotify.net.
	dnsresolver.roles.ash2.spotify.net.	300	PTR	ash2-dnsresolver-a1926.ash2.spotify.net.
	dnsresolver.roles.ash2.spotify.net.	300	PTR	ash2-dnsresolver-a3.ash2.spotify.net.
NS records:
	roles.ash2.spotify.net.	300	NS	ns2.spotify.com.
	roles.ash2.spotify.net.	300	NS	ns4.spotify.com.
	roles.ash2.spotify.net.	300	NS	ns3.spotify.com.
	roles.ash2.spotify.net.	300	NS	ns5.spotify.com.
Additional records:
```

### Actual
```
$ python -m pycares PTR dnsresolver.roles.ash2.spotify.net
ares_query_ptr_result(name='ash2-dnsresolver-a3.ash2.spotify.net', ttl=211)
```

**Comment by saghul** [comment]
Hi Lynn! That is already supported, the `aliases` attribute of the PTR result object covers it. There was, however, a bug in the string representation, so it wasn't obvious. I fixed that in https://github.com/saghul/pycares/commit/1c02900d9d7a4aec480908c383a9c87b0d10ed5b and this is the result now:

```
python -m pycares PTR dnsresolver.roles.ash2.spotify.net
ares_query_ptr_result(name='ash2-dnsresolver-a3.ash2.spotify.net', ttl=3, aliases=['ash2-dnsresolver-a1926.ash2.spotify.net', 'ash2-dnsresolver-a4.ash2.spotify.net', 'ash2-dnsresolver-a1.ash2.spotify.net', 'ash2-dnsresolver-a3.ash2.spotify.net'])
```

Can you please take the latest code from master an give it a go? The bug affected string representation only, if you are using this in an application you can access the `aliases` attribute in the result object already.

PS: :heart: Spotify.

**Comment by econchick** [comment]
Hey @saghul - thank you for the quick response! You're right, I didn't realize there was an `aliases` attribute. That indeed solves the problem for me, thank you! 

I also built off of master, and I can confirm the string repr includes the `aliases` attr. \o/

Thanks again!
