### ISSUE TITLE
Build on Solaris failed

### ISSUE THREAD

**Issue by hergla** [saghul/pycares#72]
Hi saghul,

i tried to build for solaris11. But the build failed because of two issues in setup_cares.py

$ python3 setup.py build 
creating build/temp.solaris-2.11-sun4v.32bit-3.6/deps/c-ares/src
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m32 -I/usr/include/ncurses -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/opt/OLBpython/include/python3.6m -Ideps/c-ares/src -c src/pycares.c -o build/temp.solaris-2.11-sun4v.32bit-3.6/src/pycares.o
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m32 -I/usr/include/ncurses -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/opt/OLBpython/include/python3.6m -Ideps/c-ares/src -c deps/c-ares/src/ares__close_sockets.c -o build/temp.solaris-2.11-sun4v.32bit-3.6/deps/c-ares/src/ares__close_sockets.o
In file included from deps/c-ares/src/ares__close_sockets.c:17:0:
deps/c-ares/src/ares_setup.h:32:25: fatal error: ares_config.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

diff -u setup_cares_orig.py setup_cares.py
--- setup_cares_orig.py Mon Aug 13 08:08:32 2018
+++ setup_cares.py      Mon Aug 13 08:09:59 2018
@@ -85,9 +85,10 @@
         elif sys.platform.startswith('openbsd'):
             self.compiler.add_include_dir(os.path.join(self.cares_dir, 'src/config_openbsd'))
         elif sys.platform.startswith('sunos'):
+            self.compiler.add_include_dir(os.path.join(self.cares_dir, 'src/config_sunos'))
             self.compiler.add_library('socket')
             self.compiler.add_library('nsl')
-            self.compiler.add_library('lkstat')
+            self.compiler.add_library('kstat')
         elif sys.platform == 'win32':
             self.compiler.add_include_dir(os.path.join(self.cares_dir, 'src/config_win32'))
             self.extensions[0].extra_link_args = ['/NODEFAULTLIB:libcmt']

**Comment by saghul** [comment]
Hi @hergla! Can you please send it as a PR?
