### ISSUE TITLE
formatted error messages class differs in version 3

### ISSUE THREAD

**Issue by gpatel-fr** [saghul/pycares#90]
Hello
with pycares 2.4
```
>>> pycares.errno.strerror(pycares.errno.ARES_ENOTFOUND)
'Domain name not found'
```
with pycares 3.0
```
>>> pycares.errno.strerror(pycares.errno.ARES_ENOTFOUND)
b'Domain name not found'
```
is that intended ? Feels strange to get bytes as an error message using python 3.6 or 3.7 while old version was returning a string.
Not a huge problem in real life of course but breakage are sometimes made of stuff like that (a test coverage in my case)

**Comment by saghul** [comment]
Hi!

It was partially intentional. I did a big refactor in version 3 so all DNS response types were bytes. Now, errors should still be text, just like `os.strerror`. Would you like to send a PR with a fix?

**Comment by gpatel-fr** [comment]
I'd like to be able to post a fix, but I have a long and painful experience of half baked fixes done by people (well, me, mostly) not really understanding the software they are attempting to fix, as I know nil about cffi and indeed your project (I stumbled on this while checking the coverage of another project with the PR I'm trying to do, as the last build of this project was done in January your 3.0 release in March, so officially it is still building on Travis, but no more on my computer, of course) , so let's just consider this issue as a heads-up for now, to acknowledge that yes, pycares has partially intentional changes with 3.0 (I totally love this line, I think that I will borrow it)
