### ISSUE TITLE
Non-ascii TXT records, again

### ISSUE THREAD

**Issue by huumanoid** [saghul/pycares#95]
Hey there @saghul and thank you for your effort in maintaining such a great projects as `pycares` and `aiodns`.

Sorry to say, but `bytes` vs `str` issue comes back.

Similar issues: saghul/aiodns#32 and saghul/aiodns#37 

### Issue
This domain contains a pretty long `TXT` record with non-ascii symbols in the middle:
```
import asyncio
from aiodns import DNSResolver

r = DNSResolver()
query = r.query('txt-non-ascii.dns-test.hmnid.ru', 'TXT')
asyncio.get_event_loop().run_until_complete(query)
```

Corresponding traceback:
```
From cffi callback <function _query_cb at 0x7f8e95935400>:
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/pycares/__init__.py", line 140, in _query_cb
    result, status = parse_result(query_type, abuf, alen)
  File "/lib/python3.6/site-packages/pycares/__init__.py", line 283, in parse_result
    tmp_obj.text += new_chunk.text
TypeError: must be str, not bytes
```

### Reason
1. The reply from `ares_parse_txt_reply_ext` comes in multiple parts
2. One long separate `TXT` record is split by four parts
3. The first part contains only ascii characters, but the seconds one has some non-ascii octets.
4. `maybe_str` converts the first part to `str`
5. `maybe_str` is unable to decode the second part, so returns `bytes`
6. Unable to concatenate `str` and `bytes`
7. Boom
8. The corresponding future is never resolved.

### Solution
One of the ways to fix it: do not apply `maybe_str` inside of `ares_query_txt_result`, but instead apply `maybe_str` after all results are collected. What do you think? Thanks!

**Comment by saghul** [comment]
> One of the ways to fix it: do not apply `maybe_str` inside of `ares_query_txt_result`, but instead apply `maybe_str` after all results are collected. What do you think? Thanks!

Great analysis, this makes perfect sense! Care to send a PR?

**Comment by huumanoid** [comment]
Thanks for quick reply! PR? With pleasure!
